/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --include-runtime=false` (hash: 1c0e1f60c8efabcaf7e92bce5b0d6bd2)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../worker/index");
		durableNamespaces: "RetroRoom";
	}
	interface Env {
		ROOM_CREATE_RATE_LIMITER: RateLimit;
		ROOM_ACCESS_RATE_LIMITER: RateLimit;
		ASSETS: Fetcher;
		TURNSTILE_SITE_KEY: "0x4AAAAAADHM_ojgn8qs2Xcr";
		RETRO_ROOM: DurableObjectNamespace<import("../worker/index").RetroRoom>;
	}
}
interface Env extends Cloudflare.Env {}
